# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sms.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsms.proto\x12\x03sms\"\xc9\x01\n\x0eSendSMSRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65livery_report\x18\x04 \x01(\x08\x12\x33\n\x08metadata\x18\x05 \x03(\x0b\x32!.sms.SendSMSRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd4\x01\n\x13SendBatchSMSRequest\x12\x15\n\rphone_numbers\x18\x01 \x03(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65livery_report\x18\x04 \x01(\x08\x12\x38\n\x08metadata\x18\x05 \x03(\x0b\x32&.sms.SendBatchSMSRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"@\n\x0fSendSMSResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"E\n\x14SendBatchSMSResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x14\n\x12ModemStatusRequest\"D\n\x13ModemStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"D\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x96\x02\n\nSMSService\x12\x36\n\x07SendSMS\x12\x13.sms.SendSMSRequest\x1a\x14.sms.SendSMSResponse\"\x00\x12\x45\n\x0cSendBatchSMS\x12\x18.sms.SendBatchSMSRequest\x1a\x19.sms.SendBatchSMSResponse\"\x00\x12\x42\n\x0bHealthCheck\x12\x17.sms.HealthCheckRequest\x1a\x18.sms.HealthCheckResponse\"\x00\x12\x45\n\x0eGetModemStatus\x12\x17.sms.ModemStatusRequest\x1a\x18.sms.ModemStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDSMSREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SENDSMSREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SENDBATCHSMSREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SENDBATCHSMSREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SENDSMSREQUEST']._serialized_start=19
  _globals['_SENDSMSREQUEST']._serialized_end=220
  _globals['_SENDSMSREQUEST_METADATAENTRY']._serialized_start=173
  _globals['_SENDSMSREQUEST_METADATAENTRY']._serialized_end=220
  _globals['_SENDBATCHSMSREQUEST']._serialized_start=223
  _globals['_SENDBATCHSMSREQUEST']._serialized_end=435
  _globals['_SENDBATCHSMSREQUEST_METADATAENTRY']._serialized_start=173
  _globals['_SENDBATCHSMSREQUEST_METADATAENTRY']._serialized_end=220
  _globals['_SENDSMSRESPONSE']._serialized_start=437
  _globals['_SENDSMSRESPONSE']._serialized_end=501
  _globals['_SENDBATCHSMSRESPONSE']._serialized_start=503
  _globals['_SENDBATCHSMSRESPONSE']._serialized_end=572
  _globals['_MODEMSTATUSREQUEST']._serialized_start=574
  _globals['_MODEMSTATUSREQUEST']._serialized_end=594
  _globals['_MODEMSTATUSRESPONSE']._serialized_start=596
  _globals['_MODEMSTATUSRESPONSE']._serialized_end=664
  _globals['_HEALTHCHECKREQUEST']._serialized_start=666
  _globals['_HEALTHCHECKREQUEST']._serialized_end=686
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=688
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=756
  _globals['_SMSSERVICE']._serialized_start=759
  _globals['_SMSSERVICE']._serialized_end=1037
# @@protoc_insertion_point(module_scope)
