# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import src.sms_service.sms_pb2 as sms__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SMSServiceStub(object):
    """短信服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSMS = channel.unary_unary(
                '/sms.SMSService/SendSMS',
                request_serializer=sms__pb2.SendSMSRequest.SerializeToString,
                response_deserializer=sms__pb2.SendSMSResponse.FromString,
                _registered_method=True)
        self.SendBatchSMS = channel.unary_unary(
                '/sms.SMSService/SendBatchSMS',
                request_serializer=sms__pb2.SendBatchSMSRequest.SerializeToString,
                response_deserializer=sms__pb2.SendBatchSMSResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sms.SMSService/HealthCheck',
                request_serializer=sms__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=sms__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SMSServiceServicer(object):
    """短信服务
    """

    def SendSMS(self, request, context):
        """发送单条短信
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatchSMS(self, request, context):
        """批量发送短信
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SMSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSMS': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSMS,
                    request_deserializer=sms__pb2.SendSMSRequest.FromString,
                    response_serializer=sms__pb2.SendSMSResponse.SerializeToString,
            ),
            'SendBatchSMS': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchSMS,
                    request_deserializer=sms__pb2.SendBatchSMSRequest.FromString,
                    response_serializer=sms__pb2.SendBatchSMSResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sms__pb2.HealthCheckRequest.FromString,
                    response_serializer=sms__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sms.SMSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sms.SMSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SMSService(object):
    """短信服务
    """

    @staticmethod
    def SendSMS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sms.SMSService/SendSMS',
            sms__pb2.SendSMSRequest.SerializeToString,
            sms__pb2.SendSMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBatchSMS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sms.SMSService/SendBatchSMS',
            sms__pb2.SendBatchSMSRequest.SerializeToString,
            sms__pb2.SendBatchSMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sms.SMSService/HealthCheck',
            sms__pb2.HealthCheckRequest.SerializeToString,
            sms__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
